config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

resources :pages 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
# CRUD


# read views all the pages 
  def index
    # SQL SELECT * FROM PAGES 
    @pages = Page.all
  end

  #read views a single page 
  def show
    @page = Page.find(params[:id])
    # renders a page
  end

  # read renders the form for a new page
  def new
    # CREATES NEW PAGE ONLY IN MEMORY NO IN DATABASE
    @page = Page.new
    # renders the form
  end

  # creates, creates a new page 
  def create 
    #Page.create(Title: 'fhf', body: 'hfuhf')
    @page = Page.new(pages_params)

    if @page.save
      redirect_to pages_path
    else 
      render :new

    end
  end

  # read, renders the edit form
  def edit
    @page = Page.find(params[:id])
    #render the edit form
  end
    #update, updates a page 
  def update 
    # looking for a page with a specific id 
    @pages = Page.find(params[:id])

    # updates with new information
    if @page.update(pages_params)
      redirect_to pages_path
    else 
      render :edit 
    end
  end


  # Delete, deletes a single page 
  def destroy 
    # finds and delete page 
    Page.find(params[:id]).destroy
    # take us back to all pages 
    redirect_to pages_path
  end

  private 

  def pages_params
    params.require(:page).permit(:title, :body) 

     end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # renders home views
  end

  def about
    #renders about views 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Pages', pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Form to edit items</h1>

<%= form_for @page do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :body %>
<%= f.text_area :body %>

<%= f.submit %>


<% end %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>

<% @pages.each do |page| %>
  <%= page.title %>
  <%= link_to 'show page', page_path(page) %>
  <%= link_to 'edit page', edit_page_path(page) %>
  <%= link_to 'Delete page', page, method: :delete %>

<% end %>



<%= link_to 'Add a new Page', new_page_path %>

app/views/pages/new.html.erb
<h1>Pages Form</h1>

<%= form_for @page do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>


<%= f.label :body %>
<%= f.text_area :body%>

<%= f.submit %>



 <% end %>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<%= @page.title %>
<%= @page.body %>

<%= link_to 'back', pages_path %>
<a href='/pages'>Back</a>

app/views/static_pages/about.html.erb
<h1>ALL about this webpage</h1>

app/views/static_pages/home.html.erb
<h1>This is my home page</h1>